### ISSUE TITLE
How to get it work?

### ISSUE THREAD

**Issue by railrun** [mefistotelis/pylabview#10]
Hi, 
I am trying to use your tool, but didn't get it to work. Do I need Python2 or Python3?
I tried to run the setup.py (python setup.py install).  

I am using Ubuntu 18.04

`martin@martin-ubuntu:~/Downloads/Speed/pylabview$` sudo python setup.py install
```

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to pylabview.egg-info/requires.txt
writing pylabview.egg-info/PKG-INFO
writing top-level names to pylabview.egg-info/top_level.txt
writing dependency_links to pylabview.egg-info/dependency_links.txt
writing entry points to pylabview.egg-info/entry_points.txt
reading manifest file 'pylabview.egg-info/SOURCES.txt'
writing manifest file 'pylabview.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVdatatype.py -> build/bdist.linux-i686/egg/pylabview
creating build/bdist.linux-i686/egg/pylabview/assets
copying build/lib.linux-i686-2.7/pylabview/assets/tom-thumb.txt -> build/bdist.linux-i686/egg/pylabview/assets
copying build/lib.linux-i686-2.7/pylabview/assets/tom-thumb.pil -> build/bdist.linux-i686/egg/pylabview/assets
copying build/lib.linux-i686-2.7/pylabview/assets/tom-thumb.pbm -> build/bdist.linux-i686/egg/pylabview/assets
copying build/lib.linux-i686-2.7/pylabview/LVinstrument.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVcode.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/__init__.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVlinkinfo.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVdatatyperef.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/modRSRC.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVdatafill.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVxml.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVheap.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/readRSRC.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVblock.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVmisc.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVclasses.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVparts.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib.linux-i686-2.7/pylabview/LVrsrcontainer.py -> build/bdist.linux-i686/egg/pylabview
byte-compiling build/bdist.linux-i686/egg/pylabview/LVdatatype.py to LVdatatype.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVinstrument.py to LVinstrument.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVcode.py to LVcode.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVlinkinfo.py to LVlinkinfo.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVdatatyperef.py to LVdatatyperef.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/modRSRC.py to modRSRC.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVdatafill.py to LVdatafill.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVxml.py to LVxml.pyc
  File "build/bdist.linux-i686/egg/pylabview/LVxml.py", line 36
    def __init__(self, element_factory=None, *,
                                              ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-i686/egg/pylabview/LVheap.py to LVheap.pyc
  File "build/bdist.linux-i686/egg/pylabview/LVheap.py", line 1668
    def __init__(self, *args, btlen=-1, signed=True):
                                  ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-i686/egg/pylabview/readRSRC.py to readRSRC.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVblock.py to LVblock.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVmisc.py to LVmisc.pyc
  File "build/bdist.linux-i686/egg/pylabview/LVmisc.py", line 104
    print(*args, file=sys.stderr, **kwargs)
          ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-i686/egg/pylabview/LVclasses.py to LVclasses.pyc
  File "build/bdist.linux-i686/egg/pylabview/LVclasses.py", line 244
    def __init__(self, index, *args, useConsolidatedTypes=False, expectContentKind="auto", allowFillValue=False):
                                                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-i686/egg/pylabview/LVparts.py to LVparts.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVrsrcontainer.py to LVrsrcontainer.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/entry_points.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/requires.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pylabview.modRSRC: module references __file__
creating 'dist/pylabview-0.1.1-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing pylabview-0.1.1-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/pylabview-0.1.1-py2.7.egg
Extracting pylabview-0.1.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/pylabview-0.1.1-py2.7.egg/pylabview/LVclasses.py", line 244
    def __init__(self, index, *args, useConsolidatedTypes=False, expectContentKind="auto", allowFillValue=False):
                                                        ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/pylabview-0.1.1-py2.7.egg/pylabview/LVheap.py", line 1668
    def __init__(self, *args, btlen=-1, signed=True):
                                  ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/pylabview-0.1.1-py2.7.egg/pylabview/LVmisc.py", line 104
    print(*args, file=sys.stderr, **kwargs)
          ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/pylabview-0.1.1-py2.7.egg/pylabview/LVxml.py", line 36
    def __init__(self, element_factory=None, *,
                                              ^
SyntaxError: invalid syntax

Adding pylabview 0.1.1 to easy-install.pth file
Installing readRSRC script to /usr/local/bin
Installing modRSRC script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pylabview-0.1.1-py2.7.egg
Processing dependencies for pylabview==0.1.1
Searching for Pillow==6.2.2
Best match: Pillow 6.2.2
Adding Pillow 6.2.2 to easy-install.pth file

Using /home/martin/.local/lib/python2.7/site-packages
Finished processing dependencies for pylabview==0.1.1
```

So I get some syntax errors and I don't know what I am doing wrong.

`martin@martin-ubuntu:~/Downloads/Speed/pylabview$` readRSRC --help

```
Traceback (most recent call last):
  File "/usr/local/bin/readRSRC", line 11, in <module>
    load_entry_point('pylabview==0.1.1', 'console_scripts', 'readRSRC')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pylabview-0.1.1-py2.7.egg/pylabview/readRSRC.py", line 24, in <module>
    import pylabview.LVxml as ET
  File "/usr/local/lib/python2.7/dist-packages/pylabview-0.1.1-py2.7.egg/pylabview/LVxml.py", line 36
    def __init__(self, element_factory=None, *,
                                              ^
SyntaxError: invalid syntax
```

**Comment by mefistotelis** [comment]
https://github.com/mefistotelis/pylabview/commit/145585b3a83bc35a3a545f5f1686b7eeb2889ae8#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R23

**Comment by railrun** [comment]
Hi, 
so I also tried Python3. Still not working

```
martin@martin-ubuntu:~/Downloads/Speed/pylabview$ sudo python3 setup.py install
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing pylabview.egg-info/PKG-INFO
writing dependency_links to pylabview.egg-info/dependency_links.txt
writing entry points to pylabview.egg-info/entry_points.txt
writing requirements to pylabview.egg-info/requires.txt
writing top-level names to pylabview.egg-info/top_level.txt
reading manifest file 'pylabview.egg-info/SOURCES.txt'
writing manifest file 'pylabview.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVdatatype.py -> build/bdist.linux-i686/egg/pylabview
creating build/bdist.linux-i686/egg/pylabview/assets
copying build/lib/pylabview/assets/tom-thumb.txt -> build/bdist.linux-i686/egg/pylabview/assets
copying build/lib/pylabview/assets/tom-thumb.pil -> build/bdist.linux-i686/egg/pylabview/assets
copying build/lib/pylabview/assets/tom-thumb.pbm -> build/bdist.linux-i686/egg/pylabview/assets
copying build/lib/pylabview/LVinstrument.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVcode.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/__init__.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVlinkinfo.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVdatatyperef.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/modRSRC.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVdatafill.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVxml.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVheap.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/readRSRC.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVblock.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVmisc.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVclasses.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVparts.py -> build/bdist.linux-i686/egg/pylabview
copying build/lib/pylabview/LVrsrcontainer.py -> build/bdist.linux-i686/egg/pylabview
byte-compiling build/bdist.linux-i686/egg/pylabview/LVdatatype.py to LVdatatype.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVinstrument.py to LVinstrument.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVcode.py to LVcode.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVlinkinfo.py to LVlinkinfo.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVdatatyperef.py to LVdatatyperef.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/modRSRC.py to modRSRC.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVdatafill.py to LVdatafill.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVxml.py to LVxml.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVheap.py to LVheap.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/readRSRC.py to readRSRC.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVblock.py to LVblock.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVmisc.py to LVmisc.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVclasses.py to LVclasses.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVparts.py to LVparts.cpython-36.pyc
byte-compiling build/bdist.linux-i686/egg/pylabview/LVrsrcontainer.py to LVrsrcontainer.cpython-36.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/entry_points.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/requires.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pylabview.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pylabview.__pycache__.modRSRC.cpython-36: module references __file__
creating 'dist/pylabview-0.1.1-py3.6.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing pylabview-0.1.1-py3.6.egg
creating /usr/local/lib/python3.6/dist-packages/pylabview-0.1.1-py3.6.egg
Extracting pylabview-0.1.1-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding pylabview 0.1.1 to easy-install.pth file
Installing modRSRC script to /usr/local/bin
Installing readRSRC script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/pylabview-0.1.1-py3.6.egg
Processing dependencies for pylabview==0.1.1
Searching for Pillow==5.1.0
Best match: Pillow 5.1.0
Adding Pillow 5.1.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for pylabview==0.1.1
```

```
martin@martin-ubuntu:~/Downloads/Speed/pylabview$ readRSRC --help
Traceback (most recent call last):
  File "/usr/local/bin/readRSRC", line 11, in <module>
    load_entry_point('pylabview==0.1.1', 'console_scripts', 'readRSRC')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/pylabview-0.1.1-py3.6.egg/pylabview/readRSRC.py", line 25, in <module>
    from pylabview.LVrsrcontainer import *
  File "/usr/local/lib/python3.6/dist-packages/pylabview-0.1.1-py3.6.egg/pylabview/LVrsrcontainer.py", line 23, in <module>
    import pylabview.LVblock as LVblock
  File "/usr/local/lib/python3.6/dist-packages/pylabview-0.1.1-py3.6.egg/pylabview/LVblock.py", line 27, in <module>
    from pylabview.LVdatatype import *
  File "/usr/local/lib/python3.6/dist-packages/pylabview-0.1.1-py3.6.egg/pylabview/LVdatatype.py", line 25, in <module>
    import pylabview.LVclasses as LVclasses
  File "/usr/local/lib/python3.6/dist-packages/pylabview-0.1.1-py3.6.egg/pylabview/LVclasses.py", line 23, in <module>
    import pylabview.LVdatatype as LVdatatype
AttributeError: module 'pylabview' has no attribute 'LVdatatype'
```

**Comment by mefistotelis** [comment]
No idea. Works for me. Though I'm not using it as a module.

```
# pylabview/readRSRC.py --help
usage: readRSRC.py [-h] [-i RSRC] [-m XML] [-v] [-t TEXTCP] [--raw-connectors]
                   [--print-map {RSRC,DFDS,LIbd,LIds,LIfp,LIvi,VCTP,VICD,VITS}]
                   [--keep-names]
                   (-l | -d | -x | -c | -n | -p PASSWORD | --version)

LabView RSRC files reader. Experimental tool.

optional arguments:
  -h, --help            show this help message and exit
[...]
```

**Comment by railrun** [comment]
Hi, I have managed to get it run on Windows, but now when I am trying to extract the xml from an vi-File I get the next error.

```
C:\Users\Martin\AppData\Local\Programs\Python\Python310\Lib\site-packages\pylabv
iew-0.1.1-py3.10.egg\pylabview>python readRSRC.py -vv -x -i Checksum16Bit.vi
Checksum16Bit.vi: Starting file parse for RSRC extraction
Checksum16Bit.vi: Block 'LVSR' index 0 recognized
Checksum16Bit.vi: Block 'RTSG' index 1 recognized
Checksum16Bit.vi: Block 'CCST' index 2 recognized
Checksum16Bit.vi: Block 'LIvi' index 3 recognized
Checksum16Bit.vi: Block 'CONP' index 4 recognized
Checksum16Bit.vi: Block 'TM80' index 5 recognized
Checksum16Bit.vi: Block 'DFDS' index 6 recognized
Checksum16Bit.vi: Block 'LIds' index 7 recognized
Checksum16Bit.vi: Block 'VICD' index 8 recognized
Checksum16Bit.vi: Block 'GCDI' index 9 recognized
Checksum16Bit.vi: Block 'vers' index 10 recognized
Checksum16Bit.vi: Block 'SCSR' index 11 recognized
Checksum16Bit.vi: Block 'DLDR' index 12 recognized
Checksum16Bit.vi: Block 'FPTD' index 13 recognized
Checksum16Bit.vi: Block 'CPMp' index 14 recognized
Checksum16Bit.vi: Block 'BFAL' index 15 recognized
Checksum16Bit.vi: Block 'NUID' index 16 recognized
Checksum16Bit.vi: Block 'SUID' index 17 recognized
Checksum16Bit.vi: Block 'BNID' index 18 recognized
Checksum16Bit.vi: Block 'GCPR' index 19 recognized
Checksum16Bit.vi: Block 'BDPW' index 20 recognized
Checksum16Bit.vi: Block 'VITS' index 21 recognized
Checksum16Bit.vi: Block 'VCTP' index 22 recognized
Checksum16Bit.vi: Block b'LVSR' max data size set to 144 bytes
Checksum16Bit.vi: Block b'RTSG' max data size set to 20 bytes
Checksum16Bit.vi: Block b'CCST' max data size set to 8 bytes
Checksum16Bit.vi: Block b'LIvi' max data size set to 16 bytes
Checksum16Bit.vi: Block b'CONP' max data size set to 8 bytes
Checksum16Bit.vi: Block b'TM80' max data size set to 104 bytes
Checksum16Bit.vi: Block b'DFDS' max data size set to 364 bytes
Checksum16Bit.vi: Block b'VCTP' max data size set to 5704 bytes
Checksum16Bit.vi: Block b'LIds' max data size set to 16 bytes
Checksum16Bit.vi: Block b'VICD' max data size set to 3192 bytes
Checksum16Bit.vi: Block b'GCDI' max data size set to 216 bytes
Checksum16Bit.vi: Block b'vers' max data size set to 80 bytes
Error: Block b'vers' section 4 always zero value 1 is 3 instead of 0
Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python310\Lib\site-package
s\pylabview-0.1.1-py3.10.egg\pylabview\readRSRC.py", line 222, in <module>
    main()
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python310\Lib\site-package
s\pylabview-0.1.1-py3.10.egg\pylabview\readRSRC.py", line 158, in main
    vi = VI(po, rsrc_fh=rsrc_fh, text_encoding=po.textcp)
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python310\lib\site-package
s\pylabview-0.1.1-py3.10.egg\pylabview\LVrsrcontainer.py", line 233, in __init__

    self.readRSRC(rsrc_fh)
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python310\lib\site-package
s\pylabview-0.1.1-py3.10.egg\pylabview\LVrsrcontainer.py", line 387, in readRSRC

    self.readRSRCBlockData(fh, block_headers)
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python310\lib\site-package
s\pylabview-0.1.1-py3.10.egg\pylabview\LVrsrcontainer.py", line 371, in readRSRC
BlockData
    block.parseData()
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python310\lib\site-package
s\pylabview-0.1.1-py3.10.egg\pylabview\LVblock.py", line 530, in parseData
    self.parseRSRCData(section_num, bldata)
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python310\lib\site-package
s\pylabview-0.1.1-py3.10.egg\pylabview\LVblock.py", line 3831, in parseRSRCData
    raise AttributeError("Block {} section {} always zero value 1 is {} instead
of {}"\
AttributeError: Block b'vers' section 4 always zero value 1 is 3 instead of 0

```

**Comment by mefistotelis** [comment]
https://github.com/mefistotelis/pylabview/issues/4

**Comment by mefistotelis** [comment]
Fixed with the commit:
https://github.com/mefistotelis/pylabview/commit/7b01960a1d66cec2ff583e4f876a16620c487b23
