### ISSUE TITLE
Error while using modRSRC.py

### ISSUE THREAD

**Issue by andrea1984** [mefistotelis/pylabview#5]
When I run **modRSRC.py -f -m ..\ScriptSubVIs\ReadScriptFile.xml** this error occurs:

Error: 'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "C:\Users\ccsoper\Downloads\simucam\pylabview-master\modRSRC.py", line 7715, in <module> main()
  File "C:\Users\ccsoper\Downloads\simucam\pylabview-master\modRSRC.py", line 7701, in main checkBlocksAvailable(root, po)
  File "C:\Users\ccsoper\Downloads\simucam\pylabview-master\modRSRC.py", line 7587, in checkBlocksAvailable
    makeUidsUnique(FPHP, BDHP, ver, fo, po)
  File "C:\Users\ccsoper\Downloads\simucam\pylabview-master\modRSRC.py", line 7476, in makeUidsUnique
    zPlaneList_elems = ddo.findall("./paneHierarchy/zPlaneList/SL__arrayElement[@class][@uid]")
AttributeError: 'NoneType' object has no attribute 'findall'

**Comment by andrea1984** [comment]
I added a check on ddo variable: `if ddo is not None:`
Now when I try to recreate the vi, sadly I have this error: **Inintialization from XML is not implemented**
What should I do?

**Comment by mefistotelis** [comment]
The issue should be really fixed by not adding None to the list; it is added here:

```
allDDOsWithLists.append( FPHP.find("./SL__rootObject/root/ddoList/..") )
```

For `Inintialization from XML is not implemented` - well, you'd have to implement it. From call stack, you should be able to figure out which block (which python class) raised the exception.
