### ISSUE TITLE
Error while creating VI from XML

### ISSUE THREAD

**Issue by damirsafin** [mefistotelis/pylabview#7]
Hello. Tried to create VI from fixed XML (previously extracted from VI) (by your YouTube tutorial). I got the error.

```
...
...
main.xml: Block HIST recognized
main.xml: Block PRT recognized
main.xml: Block VCTP recognized
main.xml: Block FTAB recognized
Error: Tag 'OF__StdNumMin' of Class 'SL__stdSlide' has non-hex content, but cannot get related TypeDesc
Traceback (most recent call last):
  File "readRSRC.py", line 224, in <module>
    main()
  File "readRSRC.py", line 181, in main
    vi = VI(po, xml_root=tree.getroot(), text_encoding=po.textcp)
  File "C:\LV\pylabview4\LVrsrcontainer.py", line 236, in __init__
    self.readXML(xml_root, po.xml)
  File "C:\LV\pylabview4\LVrsrcontainer.py", line 536, in readXML
    self.readXMLBlockData()
  File "C:\LV\pylabview4\LVrsrcontainer.py", line 462, in readXMLBlockData
    block.initWithXMLLate()        # Late part of initialization, which requires all blocks to be already present        for block in self.blocks.values():            block.initWithXMLLate()
  File "C:\LV\pylabview4\LVblock.py", line 5266, in initWithXMLLate
    obj.initWithXMLLate()
  File "C:\LV\pylabview4\LVheap.py", line 2137, in initWithXMLLate
    .format(self.tagEn.name, parentTopClassEn(self.parent).name))
AttributeError: Tag 'OF__StdNumMin' of Class 'SL__stdSlide' has non-hex content, but cannot get related TypeDesc
```

**Comment by mefistotelis** [comment]
First, check what happens when you do not apply any 'fix'.
If the error still persists, provide content of the `SL__stdSlide` tag.

**Comment by damirsafin** [comment]
Thanks. Now it works.
There is no such "SL__stdSlide" text in XML.
